"""Update - Product - Add length for Varchar

Revision ID: 0686d3119d3f
Revises: ac05d0baf838
Create Date: 2022-08-26 11:32:30.448408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0686d3119d3f'
down_revision = 'ac05d0baf838'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_table('product')
    # ### end Alembic commands ###
